spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?characterEncoding=UTF-8&useSSL=true&serverTimezone=UTC
    username: root
    password: Liangwy189
  thymeleaf:
    prefix: classpath:/article/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
  mvc:
    hiddenmethod:
      filter:
        enabled: true
mybatis:
  type-aliases-package: com.example.entity
  mapper-locations: classpath:/mapping/*.xml
